// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvOFWM2MAJQh0UXl9T3JZ_5f9lYMH_T7g',
    appId: '1:1101088064:android:6b4970371335a93f5266a5',
    messagingSenderId: '1101088064',
    projectId: 'communication-4166b',
    storageBucket: 'communication-4166b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZU6X8wg9lOvgzwmHkB856XNW-6XIczCw',
    appId: '1:1101088064:ios:dc8b0842178a51295266a5',
    messagingSenderId: '1101088064',
    projectId: 'communication-4166b',
    storageBucket: 'communication-4166b.appspot.com',
    androidClientId: '1101088064-540crmpkdok4oh2vbsjs8hllb75qum88.apps.googleusercontent.com',
    iosClientId: '1101088064-pb12hk3acmks4nc0v2305e5buajnplqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.communicationType',
  );
}
